# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: evaluator.proto

require 'google/protobuf'

require 'core_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "photon.EvaluationRequest" do
    optional :model_name, :string, 1
    map :features, :string, :message, 2, "photon.ValueInterface"
  end
  add_message "photon.EvaluationResponse" do
    optional :model_uid, :string, 1
    optional :version_uid, :string, 2
    optional :node, :string, 3
    map :result, :string, :message, 4, "photon.ValueInterface"
  end
end

module Photon
  EvaluationRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("photon.EvaluationRequest").msgclass
  EvaluationResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("photon.EvaluationResponse").msgclass
end
