# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: features.proto

require 'google/protobuf'

require 'core_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "photon.FeatureSet" do
    optional :id, :int64, 1
    optional :name, :string, 2
    repeated :keys, :string, 3
    repeated :fields, :message, 4, "photon.FeatureSetField"
    optional :created_at, :int32, 5
    optional :updated_at, :int32, 6
  end
  add_message "photon.FeatureSetField" do
    optional :feature_set_id, :int64, 1
    optional :name, :string, 2
    optional :value_type, :string, 3
    optional :nullable, :bool, 4
  end
  add_message "photon.FindFeatureSetRequest" do
    optional :id, :int64, 1
  end
  add_message "photon.CreateFeatureSetRequest" do
    optional :name, :string, 1
    repeated :keys, :string, 2
    repeated :fields, :message, 3, "photon.FeatureSetField"
  end
  add_message "photon.CreateFeatureSetResponse" do
    optional :id, :int64, 1
  end
  add_message "photon.DeleteFeatureSetRequest" do
    optional :id, :int64, 1
  end
end

module Photon
  FeatureSet = Google::Protobuf::DescriptorPool.generated_pool.lookup("photon.FeatureSet").msgclass
  FeatureSetField = Google::Protobuf::DescriptorPool.generated_pool.lookup("photon.FeatureSetField").msgclass
  FindFeatureSetRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("photon.FindFeatureSetRequest").msgclass
  CreateFeatureSetRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("photon.CreateFeatureSetRequest").msgclass
  CreateFeatureSetResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("photon.CreateFeatureSetResponse").msgclass
  DeleteFeatureSetRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("photon.DeleteFeatureSetRequest").msgclass
end
