# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: models.proto

require 'google/protobuf'

require 'core_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "photon.Model" do
    optional :id, :int64, 1
    optional :name, :string, 2
    optional :runner_type, :string, 3
    optional :replicas, :int32, 4
    repeated :features, :message, 5, "photon.ModelFeature"
    repeated :precomputed_features, :message, 6, "photon.ModelFeature"
    optional :created_at, :int32, 7
    optional :updated_at, :int32, 8
  end
  add_message "photon.ModelVersion" do
    optional :id, :int64, 1
    optional :model_id, :int64, 2
    optional :name, :string, 3
    optional :file_name, :string, 4
    optional :is_primary, :bool, 5
    optional :is_shadow, :bool, 6
    optional :created_at, :int32, 7
  end
  add_message "photon.ModelFeature" do
    optional :name, :string, 1
    optional :required, :bool, 2
  end
  add_message "photon.PrecomputedFeaturesSet" do
    repeated :features, :message, 1, "photon.ModelFeature"
  end
  add_message "photon.FindModelRequest" do
    optional :id, :int64, 1
  end
  add_message "photon.CreateModelRequest" do
    optional :name, :string, 1
    optional :runner_type, :string, 2
    optional :replicas, :int32, 3
    repeated :features, :message, 4, "photon.ModelFeature"
    map :precomputed_features, :int64, :message, 5, "photon.PrecomputedFeaturesSet"
  end
  add_message "photon.CreateModelResponse" do
    optional :id, :int64, 1
  end
  add_message "photon.DeleteModelRequest" do
    optional :id, :int64, 1
  end
  add_message "photon.ListVersionsRequest" do
    optional :model_id, :int64, 1
  end
  add_message "photon.FindVersionRequest" do
    optional :id, :int64, 1
  end
  add_message "photon.SetPrimaryVersionRequest" do
    optional :model_id, :int64, 1
    optional :id, :int64, 2
  end
  add_message "photon.CreateVersionRequest" do
    oneof :value do
      optional :version, :message, 1, "photon.ModelVersion"
      optional :data, :bytes, 2
    end
  end
  add_message "photon.CreateVersionResponse" do
    optional :id, :int64, 1
  end
  add_message "photon.DeleteVersionRequest" do
    optional :id, :int64, 1
  end
end

module Photon
  Model = Google::Protobuf::DescriptorPool.generated_pool.lookup("photon.Model").msgclass
  ModelVersion = Google::Protobuf::DescriptorPool.generated_pool.lookup("photon.ModelVersion").msgclass
  ModelFeature = Google::Protobuf::DescriptorPool.generated_pool.lookup("photon.ModelFeature").msgclass
  PrecomputedFeaturesSet = Google::Protobuf::DescriptorPool.generated_pool.lookup("photon.PrecomputedFeaturesSet").msgclass
  FindModelRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("photon.FindModelRequest").msgclass
  CreateModelRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("photon.CreateModelRequest").msgclass
  CreateModelResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("photon.CreateModelResponse").msgclass
  DeleteModelRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("photon.DeleteModelRequest").msgclass
  ListVersionsRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("photon.ListVersionsRequest").msgclass
  FindVersionRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("photon.FindVersionRequest").msgclass
  SetPrimaryVersionRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("photon.SetPrimaryVersionRequest").msgclass
  CreateVersionRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("photon.CreateVersionRequest").msgclass
  CreateVersionResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("photon.CreateVersionResponse").msgclass
  DeleteVersionRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("photon.DeleteVersionRequest").msgclass
end
