# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: runner.proto

require 'google/protobuf'

require 'core_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "photon.RunnerEvaluateRequest" do
    optional :version_uid, :string, 1
    map :features, :string, :message, 2, "photon.ValueInterface"
  end
  add_message "photon.RunnerEvaluateResponse" do
    map :result, :string, :message, 1, "photon.ValueInterface"
  end
end

module Photon
  RunnerEvaluateRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("photon.RunnerEvaluateRequest").msgclass
  RunnerEvaluateResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("photon.RunnerEvaluateResponse").msgclass
end
