// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protos/core.proto

/*
Package serving is a generated protocol buffer package.

It is generated from these files:
	protos/core.proto
	protos/evaluator.proto
	protos/model_manager.proto

It has these top-level messages:
	Model
	ModelVersion
	EvaluationRequest
	EvaluationResponse
	ListModelsRequest
*/
package serving

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Model struct {
	Uid       string          `protobuf:"bytes,1,opt,name=uid" json:"uid,omitempty"`
	Name      string          `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Owner     string          `protobuf:"bytes,3,opt,name=owner" json:"owner,omitempty"`
	CreatedAt int32           `protobuf:"varint,4,opt,name=created_at,json=createdAt" json:"created_at,omitempty"`
	UpdatedAt int32           `protobuf:"varint,5,opt,name=updated_at,json=updatedAt" json:"updated_at,omitempty"`
	Versions  []*ModelVersion `protobuf:"bytes,6,rep,name=versions" json:"versions,omitempty"`
}

func (m *Model) Reset()                    { *m = Model{} }
func (m *Model) String() string            { return proto.CompactTextString(m) }
func (*Model) ProtoMessage()               {}
func (*Model) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Model) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *Model) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Model) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *Model) GetCreatedAt() int32 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func (m *Model) GetUpdatedAt() int32 {
	if m != nil {
		return m.UpdatedAt
	}
	return 0
}

func (m *Model) GetVersions() []*ModelVersion {
	if m != nil {
		return m.Versions
	}
	return nil
}

type ModelVersion struct {
	Uid       string `protobuf:"bytes,1,opt,name=uid" json:"uid,omitempty"`
	CreatedAt int32  `protobuf:"varint,2,opt,name=created_at,json=createdAt" json:"created_at,omitempty"`
	UpdatedAt int32  `protobuf:"varint,3,opt,name=updated_at,json=updatedAt" json:"updated_at,omitempty"`
}

func (m *ModelVersion) Reset()                    { *m = ModelVersion{} }
func (m *ModelVersion) String() string            { return proto.CompactTextString(m) }
func (*ModelVersion) ProtoMessage()               {}
func (*ModelVersion) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *ModelVersion) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *ModelVersion) GetCreatedAt() int32 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func (m *ModelVersion) GetUpdatedAt() int32 {
	if m != nil {
		return m.UpdatedAt
	}
	return 0
}

func init() {
	proto.RegisterType((*Model)(nil), "serving.Model")
	proto.RegisterType((*ModelVersion)(nil), "serving.ModelVersion")
}

func init() { proto.RegisterFile("protos/core.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 198 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2c, 0x28, 0xca, 0x2f,
	0xc9, 0x2f, 0xd6, 0x4f, 0xce, 0x2f, 0x4a, 0xd5, 0x03, 0xb3, 0x85, 0xd8, 0x8b, 0x53, 0x8b, 0xca,
	0x32, 0xf3, 0xd2, 0x95, 0xb6, 0x30, 0x72, 0xb1, 0xfa, 0xe6, 0xa7, 0xa4, 0xe6, 0x08, 0x09, 0x70,
	0x31, 0x97, 0x66, 0xa6, 0x48, 0x30, 0x2a, 0x30, 0x6a, 0x70, 0x06, 0x81, 0x98, 0x42, 0x42, 0x5c,
	0x2c, 0x79, 0x89, 0xb9, 0xa9, 0x12, 0x4c, 0x60, 0x21, 0x30, 0x5b, 0x48, 0x84, 0x8b, 0x35, 0xbf,
	0x3c, 0x2f, 0xb5, 0x48, 0x82, 0x19, 0x2c, 0x08, 0xe1, 0x08, 0xc9, 0x72, 0x71, 0x25, 0x17, 0xa5,
	0x26, 0x96, 0xa4, 0xa6, 0xc4, 0x27, 0x96, 0x48, 0xb0, 0x28, 0x30, 0x6a, 0xb0, 0x06, 0x71, 0x42,
	0x45, 0x1c, 0x4b, 0x40, 0xd2, 0xa5, 0x05, 0x29, 0x30, 0x69, 0x56, 0x88, 0x34, 0x54, 0xc4, 0xb1,
	0x44, 0xc8, 0x90, 0x8b, 0xa3, 0x2c, 0xb5, 0xa8, 0x38, 0x33, 0x3f, 0xaf, 0x58, 0x82, 0x4d, 0x81,
	0x59, 0x83, 0xdb, 0x48, 0x54, 0x0f, 0xea, 0x3e, 0x3d, 0xb0, 0xdb, 0xc2, 0x20, 0xb2, 0x41, 0x70,
	0x65, 0x4a, 0x71, 0x5c, 0x3c, 0xc8, 0x32, 0x58, 0x1c, 0x8f, 0xea, 0x24, 0x26, 0xfc, 0x4e, 0x62,
	0x46, 0x73, 0x52, 0x12, 0x1b, 0x38, 0x98, 0x8c, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0x93, 0x11,
	0x8d, 0x3e, 0x3b, 0x01, 0x00, 0x00,
}
