// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protos/features.proto

package serving

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type FeatureSet struct {
	Uid       string   `protobuf:"bytes,1,opt,name=uid" json:"uid,omitempty"`
	Name      string   `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Keys      []string `protobuf:"bytes,3,rep,name=keys" json:"keys,omitempty"`
	CreatedAt int32    `protobuf:"varint,4,opt,name=created_at,json=createdAt" json:"created_at,omitempty"`
	UpdatedAt int32    `protobuf:"varint,5,opt,name=updated_at,json=updatedAt" json:"updated_at,omitempty"`
}

func (m *FeatureSet) Reset()                    { *m = FeatureSet{} }
func (m *FeatureSet) String() string            { return proto.CompactTextString(m) }
func (*FeatureSet) ProtoMessage()               {}
func (*FeatureSet) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{0} }

func (m *FeatureSet) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *FeatureSet) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *FeatureSet) GetKeys() []string {
	if m != nil {
		return m.Keys
	}
	return nil
}

func (m *FeatureSet) GetCreatedAt() int32 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func (m *FeatureSet) GetUpdatedAt() int32 {
	if m != nil {
		return m.UpdatedAt
	}
	return 0
}

type FeatureSetSchema struct {
	Uid    string            `protobuf:"bytes,1,opt,name=uid" json:"uid,omitempty"`
	Schema map[string]string `protobuf:"bytes,2,rep,name=schema" json:"schema,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *FeatureSetSchema) Reset()                    { *m = FeatureSetSchema{} }
func (m *FeatureSetSchema) String() string            { return proto.CompactTextString(m) }
func (*FeatureSetSchema) ProtoMessage()               {}
func (*FeatureSetSchema) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{1} }

func (m *FeatureSetSchema) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *FeatureSetSchema) GetSchema() map[string]string {
	if m != nil {
		return m.Schema
	}
	return nil
}

type ListFeatureSetsRequest struct {
}

func (m *ListFeatureSetsRequest) Reset()                    { *m = ListFeatureSetsRequest{} }
func (m *ListFeatureSetsRequest) String() string            { return proto.CompactTextString(m) }
func (*ListFeatureSetsRequest) ProtoMessage()               {}
func (*ListFeatureSetsRequest) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{2} }

type FindFeatureSetRequest struct {
	Uid string `protobuf:"bytes,1,opt,name=uid" json:"uid,omitempty"`
}

func (m *FindFeatureSetRequest) Reset()                    { *m = FindFeatureSetRequest{} }
func (m *FindFeatureSetRequest) String() string            { return proto.CompactTextString(m) }
func (*FindFeatureSetRequest) ProtoMessage()               {}
func (*FindFeatureSetRequest) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{3} }

func (m *FindFeatureSetRequest) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

type CreateFeatureSetRequest struct {
	Name string   `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Keys []string `protobuf:"bytes,2,rep,name=keys" json:"keys,omitempty"`
}

func (m *CreateFeatureSetRequest) Reset()                    { *m = CreateFeatureSetRequest{} }
func (m *CreateFeatureSetRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateFeatureSetRequest) ProtoMessage()               {}
func (*CreateFeatureSetRequest) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{4} }

func (m *CreateFeatureSetRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateFeatureSetRequest) GetKeys() []string {
	if m != nil {
		return m.Keys
	}
	return nil
}

type DeleteFeatureSetRequest struct {
	Uid string `protobuf:"bytes,1,opt,name=uid" json:"uid,omitempty"`
}

func (m *DeleteFeatureSetRequest) Reset()                    { *m = DeleteFeatureSetRequest{} }
func (m *DeleteFeatureSetRequest) String() string            { return proto.CompactTextString(m) }
func (*DeleteFeatureSetRequest) ProtoMessage()               {}
func (*DeleteFeatureSetRequest) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{5} }

func (m *DeleteFeatureSetRequest) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

type ListFeatureSetSchemasRequest struct {
	FeatureSetUid string `protobuf:"bytes,1,opt,name=feature_set_uid,json=featureSetUid" json:"feature_set_uid,omitempty"`
}

func (m *ListFeatureSetSchemasRequest) Reset()                    { *m = ListFeatureSetSchemasRequest{} }
func (m *ListFeatureSetSchemasRequest) String() string            { return proto.CompactTextString(m) }
func (*ListFeatureSetSchemasRequest) ProtoMessage()               {}
func (*ListFeatureSetSchemasRequest) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{6} }

func (m *ListFeatureSetSchemasRequest) GetFeatureSetUid() string {
	if m != nil {
		return m.FeatureSetUid
	}
	return ""
}

type FindFeatureSetSchemaRequest struct {
	Uid string `protobuf:"bytes,1,opt,name=uid" json:"uid,omitempty"`
}

func (m *FindFeatureSetSchemaRequest) Reset()                    { *m = FindFeatureSetSchemaRequest{} }
func (m *FindFeatureSetSchemaRequest) String() string            { return proto.CompactTextString(m) }
func (*FindFeatureSetSchemaRequest) ProtoMessage()               {}
func (*FindFeatureSetSchemaRequest) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{7} }

func (m *FindFeatureSetSchemaRequest) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

type CreateFeatureSetSchemaRequest struct {
	FeatureSetUid string            `protobuf:"bytes,1,opt,name=feature_set_uid,json=featureSetUid" json:"feature_set_uid,omitempty"`
	Schema        map[string]string `protobuf:"bytes,2,rep,name=schema" json:"schema,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *CreateFeatureSetSchemaRequest) Reset()                    { *m = CreateFeatureSetSchemaRequest{} }
func (m *CreateFeatureSetSchemaRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateFeatureSetSchemaRequest) ProtoMessage()               {}
func (*CreateFeatureSetSchemaRequest) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{8} }

func (m *CreateFeatureSetSchemaRequest) GetFeatureSetUid() string {
	if m != nil {
		return m.FeatureSetUid
	}
	return ""
}

func (m *CreateFeatureSetSchemaRequest) GetSchema() map[string]string {
	if m != nil {
		return m.Schema
	}
	return nil
}

type DeleteFeatureSetSchemaRequest struct {
	Uid string `protobuf:"bytes,1,opt,name=uid" json:"uid,omitempty"`
}

func (m *DeleteFeatureSetSchemaRequest) Reset()                    { *m = DeleteFeatureSetSchemaRequest{} }
func (m *DeleteFeatureSetSchemaRequest) String() string            { return proto.CompactTextString(m) }
func (*DeleteFeatureSetSchemaRequest) ProtoMessage()               {}
func (*DeleteFeatureSetSchemaRequest) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{9} }

func (m *DeleteFeatureSetSchemaRequest) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func init() {
	proto.RegisterType((*FeatureSet)(nil), "serving.FeatureSet")
	proto.RegisterType((*FeatureSetSchema)(nil), "serving.FeatureSetSchema")
	proto.RegisterType((*ListFeatureSetsRequest)(nil), "serving.ListFeatureSetsRequest")
	proto.RegisterType((*FindFeatureSetRequest)(nil), "serving.FindFeatureSetRequest")
	proto.RegisterType((*CreateFeatureSetRequest)(nil), "serving.CreateFeatureSetRequest")
	proto.RegisterType((*DeleteFeatureSetRequest)(nil), "serving.DeleteFeatureSetRequest")
	proto.RegisterType((*ListFeatureSetSchemasRequest)(nil), "serving.ListFeatureSetSchemasRequest")
	proto.RegisterType((*FindFeatureSetSchemaRequest)(nil), "serving.FindFeatureSetSchemaRequest")
	proto.RegisterType((*CreateFeatureSetSchemaRequest)(nil), "serving.CreateFeatureSetSchemaRequest")
	proto.RegisterType((*DeleteFeatureSetSchemaRequest)(nil), "serving.DeleteFeatureSetSchemaRequest")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for FeaturesService service

type FeaturesServiceClient interface {
	List(ctx context.Context, in *ListFeatureSetsRequest, opts ...grpc.CallOption) (FeaturesService_ListClient, error)
	Find(ctx context.Context, in *FindFeatureSetRequest, opts ...grpc.CallOption) (*FeatureSet, error)
	Create(ctx context.Context, in *CreateFeatureSetRequest, opts ...grpc.CallOption) (*FeatureSet, error)
	Delete(ctx context.Context, in *DeleteFeatureSetRequest, opts ...grpc.CallOption) (*EmptyResponse, error)
	// Schemas
	ListSchemas(ctx context.Context, in *ListFeatureSetSchemasRequest, opts ...grpc.CallOption) (FeaturesService_ListSchemasClient, error)
	FindSchema(ctx context.Context, in *FindFeatureSetSchemaRequest, opts ...grpc.CallOption) (*FeatureSetSchema, error)
	CreateSchema(ctx context.Context, in *CreateFeatureSetSchemaRequest, opts ...grpc.CallOption) (*FeatureSetSchema, error)
	DeleteSchema(ctx context.Context, in *DeleteFeatureSetSchemaRequest, opts ...grpc.CallOption) (*EmptyResponse, error)
}

type featuresServiceClient struct {
	cc *grpc.ClientConn
}

func NewFeaturesServiceClient(cc *grpc.ClientConn) FeaturesServiceClient {
	return &featuresServiceClient{cc}
}

func (c *featuresServiceClient) List(ctx context.Context, in *ListFeatureSetsRequest, opts ...grpc.CallOption) (FeaturesService_ListClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_FeaturesService_serviceDesc.Streams[0], c.cc, "/serving.FeaturesService/List", opts...)
	if err != nil {
		return nil, err
	}
	x := &featuresServiceListClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type FeaturesService_ListClient interface {
	Recv() (*FeatureSet, error)
	grpc.ClientStream
}

type featuresServiceListClient struct {
	grpc.ClientStream
}

func (x *featuresServiceListClient) Recv() (*FeatureSet, error) {
	m := new(FeatureSet)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *featuresServiceClient) Find(ctx context.Context, in *FindFeatureSetRequest, opts ...grpc.CallOption) (*FeatureSet, error) {
	out := new(FeatureSet)
	err := grpc.Invoke(ctx, "/serving.FeaturesService/Find", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *featuresServiceClient) Create(ctx context.Context, in *CreateFeatureSetRequest, opts ...grpc.CallOption) (*FeatureSet, error) {
	out := new(FeatureSet)
	err := grpc.Invoke(ctx, "/serving.FeaturesService/Create", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *featuresServiceClient) Delete(ctx context.Context, in *DeleteFeatureSetRequest, opts ...grpc.CallOption) (*EmptyResponse, error) {
	out := new(EmptyResponse)
	err := grpc.Invoke(ctx, "/serving.FeaturesService/Delete", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *featuresServiceClient) ListSchemas(ctx context.Context, in *ListFeatureSetSchemasRequest, opts ...grpc.CallOption) (FeaturesService_ListSchemasClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_FeaturesService_serviceDesc.Streams[1], c.cc, "/serving.FeaturesService/ListSchemas", opts...)
	if err != nil {
		return nil, err
	}
	x := &featuresServiceListSchemasClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type FeaturesService_ListSchemasClient interface {
	Recv() (*FeatureSetSchema, error)
	grpc.ClientStream
}

type featuresServiceListSchemasClient struct {
	grpc.ClientStream
}

func (x *featuresServiceListSchemasClient) Recv() (*FeatureSetSchema, error) {
	m := new(FeatureSetSchema)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *featuresServiceClient) FindSchema(ctx context.Context, in *FindFeatureSetSchemaRequest, opts ...grpc.CallOption) (*FeatureSetSchema, error) {
	out := new(FeatureSetSchema)
	err := grpc.Invoke(ctx, "/serving.FeaturesService/FindSchema", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *featuresServiceClient) CreateSchema(ctx context.Context, in *CreateFeatureSetSchemaRequest, opts ...grpc.CallOption) (*FeatureSetSchema, error) {
	out := new(FeatureSetSchema)
	err := grpc.Invoke(ctx, "/serving.FeaturesService/CreateSchema", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *featuresServiceClient) DeleteSchema(ctx context.Context, in *DeleteFeatureSetSchemaRequest, opts ...grpc.CallOption) (*EmptyResponse, error) {
	out := new(EmptyResponse)
	err := grpc.Invoke(ctx, "/serving.FeaturesService/DeleteSchema", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for FeaturesService service

type FeaturesServiceServer interface {
	List(*ListFeatureSetsRequest, FeaturesService_ListServer) error
	Find(context.Context, *FindFeatureSetRequest) (*FeatureSet, error)
	Create(context.Context, *CreateFeatureSetRequest) (*FeatureSet, error)
	Delete(context.Context, *DeleteFeatureSetRequest) (*EmptyResponse, error)
	// Schemas
	ListSchemas(*ListFeatureSetSchemasRequest, FeaturesService_ListSchemasServer) error
	FindSchema(context.Context, *FindFeatureSetSchemaRequest) (*FeatureSetSchema, error)
	CreateSchema(context.Context, *CreateFeatureSetSchemaRequest) (*FeatureSetSchema, error)
	DeleteSchema(context.Context, *DeleteFeatureSetSchemaRequest) (*EmptyResponse, error)
}

func RegisterFeaturesServiceServer(s *grpc.Server, srv FeaturesServiceServer) {
	s.RegisterService(&_FeaturesService_serviceDesc, srv)
}

func _FeaturesService_List_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ListFeatureSetsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(FeaturesServiceServer).List(m, &featuresServiceListServer{stream})
}

type FeaturesService_ListServer interface {
	Send(*FeatureSet) error
	grpc.ServerStream
}

type featuresServiceListServer struct {
	grpc.ServerStream
}

func (x *featuresServiceListServer) Send(m *FeatureSet) error {
	return x.ServerStream.SendMsg(m)
}

func _FeaturesService_Find_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindFeatureSetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FeaturesServiceServer).Find(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/serving.FeaturesService/Find",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FeaturesServiceServer).Find(ctx, req.(*FindFeatureSetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FeaturesService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateFeatureSetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FeaturesServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/serving.FeaturesService/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FeaturesServiceServer).Create(ctx, req.(*CreateFeatureSetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FeaturesService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteFeatureSetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FeaturesServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/serving.FeaturesService/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FeaturesServiceServer).Delete(ctx, req.(*DeleteFeatureSetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FeaturesService_ListSchemas_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ListFeatureSetSchemasRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(FeaturesServiceServer).ListSchemas(m, &featuresServiceListSchemasServer{stream})
}

type FeaturesService_ListSchemasServer interface {
	Send(*FeatureSetSchema) error
	grpc.ServerStream
}

type featuresServiceListSchemasServer struct {
	grpc.ServerStream
}

func (x *featuresServiceListSchemasServer) Send(m *FeatureSetSchema) error {
	return x.ServerStream.SendMsg(m)
}

func _FeaturesService_FindSchema_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindFeatureSetSchemaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FeaturesServiceServer).FindSchema(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/serving.FeaturesService/FindSchema",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FeaturesServiceServer).FindSchema(ctx, req.(*FindFeatureSetSchemaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FeaturesService_CreateSchema_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateFeatureSetSchemaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FeaturesServiceServer).CreateSchema(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/serving.FeaturesService/CreateSchema",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FeaturesServiceServer).CreateSchema(ctx, req.(*CreateFeatureSetSchemaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FeaturesService_DeleteSchema_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteFeatureSetSchemaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FeaturesServiceServer).DeleteSchema(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/serving.FeaturesService/DeleteSchema",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FeaturesServiceServer).DeleteSchema(ctx, req.(*DeleteFeatureSetSchemaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _FeaturesService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "serving.FeaturesService",
	HandlerType: (*FeaturesServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Find",
			Handler:    _FeaturesService_Find_Handler,
		},
		{
			MethodName: "Create",
			Handler:    _FeaturesService_Create_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _FeaturesService_Delete_Handler,
		},
		{
			MethodName: "FindSchema",
			Handler:    _FeaturesService_FindSchema_Handler,
		},
		{
			MethodName: "CreateSchema",
			Handler:    _FeaturesService_CreateSchema_Handler,
		},
		{
			MethodName: "DeleteSchema",
			Handler:    _FeaturesService_DeleteSchema_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "List",
			Handler:       _FeaturesService_List_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "ListSchemas",
			Handler:       _FeaturesService_ListSchemas_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "protos/features.proto",
}

func init() { proto.RegisterFile("protos/features.proto", fileDescriptor2) }

var fileDescriptor2 = []byte{
	// 513 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x54, 0x4f, 0x6f, 0xd3, 0x4e,
	0x10, 0xd5, 0x26, 0x4e, 0x7e, 0xea, 0xa4, 0x3f, 0xb5, 0x0c, 0xb4, 0x35, 0x86, 0x80, 0x65, 0xd1,
	0x2a, 0x08, 0x29, 0x2d, 0xe1, 0xc2, 0x1f, 0x01, 0x0a, 0xd0, 0x1c, 0x10, 0x20, 0xd5, 0x11, 0xe7,
	0xc8, 0xc4, 0x53, 0xb0, 0xd2, 0x38, 0xc1, 0xbb, 0xae, 0xe4, 0x3b, 0x9f, 0x83, 0x8f, 0xc4, 0x99,
	0x8f, 0x83, 0xd6, 0xbb, 0x8e, 0xeb, 0xc4, 0x36, 0x3d, 0x70, 0xca, 0xee, 0xbc, 0x9d, 0x37, 0x33,
	0x6f, 0x5e, 0x0c, 0x7b, 0xcb, 0x68, 0x21, 0x16, 0xfc, 0xf8, 0x9c, 0x3c, 0x11, 0x47, 0xc4, 0xfb,
	0xe9, 0x1d, 0xff, 0xe3, 0x14, 0x5d, 0x06, 0xe1, 0x57, 0xeb, 0x86, 0xc6, 0xa7, 0x8b, 0x88, 0x14,
	0xe6, 0xfc, 0x60, 0x00, 0x23, 0xf5, 0x7c, 0x4c, 0x02, 0x77, 0xa1, 0x19, 0x07, 0xbe, 0xc9, 0x6c,
	0xd6, 0xdb, 0x72, 0xe5, 0x11, 0x11, 0x8c, 0xd0, 0x9b, 0x93, 0xd9, 0x48, 0x43, 0xe9, 0x59, 0xc6,
	0x66, 0x94, 0x70, 0xb3, 0x69, 0x37, 0x65, 0x4c, 0x9e, 0xb1, 0x0b, 0x30, 0x8d, 0xc8, 0x13, 0xe4,
	0x4f, 0x3c, 0x61, 0x1a, 0x36, 0xeb, 0xb5, 0xdc, 0x2d, 0x1d, 0x19, 0x0a, 0x09, 0xc7, 0x4b, 0x3f,
	0x83, 0x5b, 0x0a, 0xd6, 0x91, 0xa1, 0x70, 0x7e, 0x32, 0xd8, 0xcd, 0xdb, 0x18, 0x4f, 0xbf, 0xd1,
	0xdc, 0x2b, 0x69, 0xe6, 0x25, 0xb4, 0x79, 0x8a, 0x99, 0x0d, 0xbb, 0xd9, 0xeb, 0x0c, 0x0e, 0xfb,
	0x7a, 0xb4, 0xfe, 0x7a, 0x72, 0x5f, 0xfd, 0x9c, 0x86, 0x22, 0x4a, 0x5c, 0x9d, 0x64, 0x3d, 0x83,
	0xce, 0x95, 0xb0, 0xe4, 0x9f, 0x51, 0x92, 0xf1, 0xcf, 0x28, 0xc1, 0x5b, 0xd0, 0xba, 0xf4, 0x2e,
	0xe2, 0x6c, 0x5a, 0x75, 0x79, 0xde, 0x78, 0xca, 0x1c, 0x13, 0xf6, 0x3f, 0x04, 0x5c, 0xe4, 0x65,
	0xb8, 0x4b, 0xdf, 0x63, 0xe2, 0xc2, 0x79, 0x08, 0x7b, 0xa3, 0x20, 0xf4, 0x73, 0x44, 0x03, 0x9b,
	0xed, 0x3b, 0x43, 0x38, 0x78, 0x9b, 0x2a, 0xb2, 0xf9, 0x38, 0x93, 0x99, 0x95, 0xc8, 0xdc, 0xc8,
	0x65, 0x76, 0x1e, 0xc1, 0xc1, 0x3b, 0xba, 0xa0, 0x32, 0x8a, 0xcd, 0x7a, 0x23, 0xb8, 0x5b, 0x6c,
	0x5a, 0x4d, 0x9f, 0xb5, 0x8e, 0x47, 0xb0, 0xa3, 0xad, 0x32, 0xe1, 0x24, 0x26, 0x79, 0xf6, 0xff,
	0xe7, 0xab, 0x94, 0xcf, 0x81, 0xef, 0x1c, 0xc3, 0x9d, 0xe2, 0x88, 0x8a, 0xa7, 0xba, 0xf0, 0x2f,
	0x06, 0xdd, 0xf5, 0x49, 0x8b, 0x39, 0xd7, 0x2c, 0x8d, 0xef, 0xd7, 0x36, 0x3e, 0x58, 0x6d, 0xbc,
	0x96, 0xff, 0x5f, 0xaf, 0xff, 0x31, 0x74, 0xd7, 0x65, 0xff, 0x8b, 0x06, 0x83, 0xdf, 0x06, 0xec,
	0xe8, 0xd7, 0x7c, 0x2c, 0x7b, 0x9e, 0x12, 0xbe, 0x02, 0x43, 0x2e, 0x04, 0xef, 0xaf, 0xa6, 0x28,
	0x37, 0x95, 0x75, 0xb3, 0xc4, 0xd8, 0x27, 0x0c, 0x5f, 0x80, 0x21, 0x17, 0x81, 0xf7, 0x72, 0xb8,
	0xcc, 0x7a, 0xa5, 0xe9, 0xf8, 0x1a, 0xda, 0x4a, 0x33, 0xb4, 0x2b, 0x45, 0xac, 0x25, 0x78, 0x03,
	0x6d, 0x25, 0xc2, 0x15, 0x82, 0x0a, 0x33, 0x5a, 0xfb, 0xab, 0x17, 0xa7, 0xf3, 0xa5, 0x48, 0x5c,
	0xe2, 0xcb, 0x45, 0xc8, 0x09, 0xcf, 0xa0, 0x23, 0x47, 0xd6, 0x46, 0xc4, 0xc3, 0x0a, 0x21, 0x8a,
	0x46, 0xb5, 0x6e, 0x57, 0xfe, 0xcf, 0x4f, 0x18, 0x7e, 0x04, 0x90, 0x2a, 0xe8, 0x8f, 0xc6, 0x83,
	0x0a, 0x69, 0x0a, 0xeb, 0xaa, 0x21, 0xc4, 0x33, 0xd8, 0x56, 0xaa, 0xe8, 0xfb, 0xd1, 0xf5, 0x1c,
	0x57, 0x47, 0xf9, 0x09, 0xb6, 0x95, 0x4e, 0x1b, 0x94, 0xb5, 0xa6, 0xaa, 0x12, 0xf1, 0x4b, 0x3b,
	0xfd, 0x76, 0x3f, 0xf9, 0x13, 0x00, 0x00, 0xff, 0xff, 0x4c, 0x92, 0x6d, 0xa6, 0xf0, 0x05, 0x00,
	0x00,
}
