# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: core.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='core.proto',
  package='photon',
  syntax='proto3',
  serialized_pb=_b('\n\ncore.proto\x12\x06photon\"\xed\x02\n\x0eValueInterface\x12\x17\n\rvalue_boolean\x18\x01 \x01(\x08H\x00\x12\x15\n\x0bvalue_int32\x18\x02 \x01(\x05H\x00\x12\'\n\nlist_int32\x18\x03 \x01(\x0b\x32\x11.photon.ListInt32H\x00\x12\x15\n\x0bvalue_int64\x18\x04 \x01(\x03H\x00\x12\'\n\nlist_int64\x18\x05 \x01(\x0b\x32\x11.photon.ListInt64H\x00\x12\x17\n\rvalue_float32\x18\x06 \x01(\x02H\x00\x12+\n\x0clist_float32\x18\x07 \x01(\x0b\x32\x13.photon.ListFloat32H\x00\x12\x17\n\rvalue_float64\x18\x08 \x01(\x01H\x00\x12+\n\x0clist_float64\x18\t \x01(\x0b\x32\x13.photon.ListFloat64H\x00\x12\x16\n\x0cvalue_string\x18\n \x01(\tH\x00\x12\x15\n\x0bvalue_bytes\x18\x0b \x01(\x0cH\x00\x42\x07\n\x05value\"\x1a\n\tListInt32\x12\r\n\x05value\x18\x01 \x03(\x05\"\x1a\n\tListInt64\x12\r\n\x05value\x18\x01 \x03(\x03\"\x1c\n\x0bListFloat32\x12\r\n\x05value\x18\x01 \x03(\x02\"\x1c\n\x0bListFloat64\x12\r\n\x05value\x18\x01 \x03(\x01\"\x0e\n\x0c\x45mptyRequest\"\x0f\n\rEmptyResponse\"2\n\x08\x44\x61taBlob\x12\x0e\n\x04name\x18\x01 \x01(\tH\x00\x12\x0e\n\x04\x64\x61ta\x18\x02 \x01(\x0cH\x00\x42\x06\n\x04partb\x06proto3')
)




_VALUEINTERFACE = _descriptor.Descriptor(
  name='ValueInterface',
  full_name='photon.ValueInterface',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value_boolean', full_name='photon.ValueInterface.value_boolean', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='value_int32', full_name='photon.ValueInterface.value_int32', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='list_int32', full_name='photon.ValueInterface.list_int32', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='value_int64', full_name='photon.ValueInterface.value_int64', index=3,
      number=4, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='list_int64', full_name='photon.ValueInterface.list_int64', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='value_float32', full_name='photon.ValueInterface.value_float32', index=5,
      number=6, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='list_float32', full_name='photon.ValueInterface.list_float32', index=6,
      number=7, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='value_float64', full_name='photon.ValueInterface.value_float64', index=7,
      number=8, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='list_float64', full_name='photon.ValueInterface.list_float64', index=8,
      number=9, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='value_string', full_name='photon.ValueInterface.value_string', index=9,
      number=10, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='value_bytes', full_name='photon.ValueInterface.value_bytes', index=10,
      number=11, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='value', full_name='photon.ValueInterface.value',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=23,
  serialized_end=388,
)


_LISTINT32 = _descriptor.Descriptor(
  name='ListInt32',
  full_name='photon.ListInt32',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='photon.ListInt32.value', index=0,
      number=1, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=390,
  serialized_end=416,
)


_LISTINT64 = _descriptor.Descriptor(
  name='ListInt64',
  full_name='photon.ListInt64',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='photon.ListInt64.value', index=0,
      number=1, type=3, cpp_type=2, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=418,
  serialized_end=444,
)


_LISTFLOAT32 = _descriptor.Descriptor(
  name='ListFloat32',
  full_name='photon.ListFloat32',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='photon.ListFloat32.value', index=0,
      number=1, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=446,
  serialized_end=474,
)


_LISTFLOAT64 = _descriptor.Descriptor(
  name='ListFloat64',
  full_name='photon.ListFloat64',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='photon.ListFloat64.value', index=0,
      number=1, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=476,
  serialized_end=504,
)


_EMPTYREQUEST = _descriptor.Descriptor(
  name='EmptyRequest',
  full_name='photon.EmptyRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=506,
  serialized_end=520,
)


_EMPTYRESPONSE = _descriptor.Descriptor(
  name='EmptyResponse',
  full_name='photon.EmptyResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=522,
  serialized_end=537,
)


_DATABLOB = _descriptor.Descriptor(
  name='DataBlob',
  full_name='photon.DataBlob',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='photon.DataBlob.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='data', full_name='photon.DataBlob.data', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='part', full_name='photon.DataBlob.part',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=539,
  serialized_end=589,
)

_VALUEINTERFACE.fields_by_name['list_int32'].message_type = _LISTINT32
_VALUEINTERFACE.fields_by_name['list_int64'].message_type = _LISTINT64
_VALUEINTERFACE.fields_by_name['list_float32'].message_type = _LISTFLOAT32
_VALUEINTERFACE.fields_by_name['list_float64'].message_type = _LISTFLOAT64
_VALUEINTERFACE.oneofs_by_name['value'].fields.append(
  _VALUEINTERFACE.fields_by_name['value_boolean'])
_VALUEINTERFACE.fields_by_name['value_boolean'].containing_oneof = _VALUEINTERFACE.oneofs_by_name['value']
_VALUEINTERFACE.oneofs_by_name['value'].fields.append(
  _VALUEINTERFACE.fields_by_name['value_int32'])
_VALUEINTERFACE.fields_by_name['value_int32'].containing_oneof = _VALUEINTERFACE.oneofs_by_name['value']
_VALUEINTERFACE.oneofs_by_name['value'].fields.append(
  _VALUEINTERFACE.fields_by_name['list_int32'])
_VALUEINTERFACE.fields_by_name['list_int32'].containing_oneof = _VALUEINTERFACE.oneofs_by_name['value']
_VALUEINTERFACE.oneofs_by_name['value'].fields.append(
  _VALUEINTERFACE.fields_by_name['value_int64'])
_VALUEINTERFACE.fields_by_name['value_int64'].containing_oneof = _VALUEINTERFACE.oneofs_by_name['value']
_VALUEINTERFACE.oneofs_by_name['value'].fields.append(
  _VALUEINTERFACE.fields_by_name['list_int64'])
_VALUEINTERFACE.fields_by_name['list_int64'].containing_oneof = _VALUEINTERFACE.oneofs_by_name['value']
_VALUEINTERFACE.oneofs_by_name['value'].fields.append(
  _VALUEINTERFACE.fields_by_name['value_float32'])
_VALUEINTERFACE.fields_by_name['value_float32'].containing_oneof = _VALUEINTERFACE.oneofs_by_name['value']
_VALUEINTERFACE.oneofs_by_name['value'].fields.append(
  _VALUEINTERFACE.fields_by_name['list_float32'])
_VALUEINTERFACE.fields_by_name['list_float32'].containing_oneof = _VALUEINTERFACE.oneofs_by_name['value']
_VALUEINTERFACE.oneofs_by_name['value'].fields.append(
  _VALUEINTERFACE.fields_by_name['value_float64'])
_VALUEINTERFACE.fields_by_name['value_float64'].containing_oneof = _VALUEINTERFACE.oneofs_by_name['value']
_VALUEINTERFACE.oneofs_by_name['value'].fields.append(
  _VALUEINTERFACE.fields_by_name['list_float64'])
_VALUEINTERFACE.fields_by_name['list_float64'].containing_oneof = _VALUEINTERFACE.oneofs_by_name['value']
_VALUEINTERFACE.oneofs_by_name['value'].fields.append(
  _VALUEINTERFACE.fields_by_name['value_string'])
_VALUEINTERFACE.fields_by_name['value_string'].containing_oneof = _VALUEINTERFACE.oneofs_by_name['value']
_VALUEINTERFACE.oneofs_by_name['value'].fields.append(
  _VALUEINTERFACE.fields_by_name['value_bytes'])
_VALUEINTERFACE.fields_by_name['value_bytes'].containing_oneof = _VALUEINTERFACE.oneofs_by_name['value']
_DATABLOB.oneofs_by_name['part'].fields.append(
  _DATABLOB.fields_by_name['name'])
_DATABLOB.fields_by_name['name'].containing_oneof = _DATABLOB.oneofs_by_name['part']
_DATABLOB.oneofs_by_name['part'].fields.append(
  _DATABLOB.fields_by_name['data'])
_DATABLOB.fields_by_name['data'].containing_oneof = _DATABLOB.oneofs_by_name['part']
DESCRIPTOR.message_types_by_name['ValueInterface'] = _VALUEINTERFACE
DESCRIPTOR.message_types_by_name['ListInt32'] = _LISTINT32
DESCRIPTOR.message_types_by_name['ListInt64'] = _LISTINT64
DESCRIPTOR.message_types_by_name['ListFloat32'] = _LISTFLOAT32
DESCRIPTOR.message_types_by_name['ListFloat64'] = _LISTFLOAT64
DESCRIPTOR.message_types_by_name['EmptyRequest'] = _EMPTYREQUEST
DESCRIPTOR.message_types_by_name['EmptyResponse'] = _EMPTYRESPONSE
DESCRIPTOR.message_types_by_name['DataBlob'] = _DATABLOB
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ValueInterface = _reflection.GeneratedProtocolMessageType('ValueInterface', (_message.Message,), dict(
  DESCRIPTOR = _VALUEINTERFACE,
  __module__ = 'core_pb2'
  # @@protoc_insertion_point(class_scope:photon.ValueInterface)
  ))
_sym_db.RegisterMessage(ValueInterface)

ListInt32 = _reflection.GeneratedProtocolMessageType('ListInt32', (_message.Message,), dict(
  DESCRIPTOR = _LISTINT32,
  __module__ = 'core_pb2'
  # @@protoc_insertion_point(class_scope:photon.ListInt32)
  ))
_sym_db.RegisterMessage(ListInt32)

ListInt64 = _reflection.GeneratedProtocolMessageType('ListInt64', (_message.Message,), dict(
  DESCRIPTOR = _LISTINT64,
  __module__ = 'core_pb2'
  # @@protoc_insertion_point(class_scope:photon.ListInt64)
  ))
_sym_db.RegisterMessage(ListInt64)

ListFloat32 = _reflection.GeneratedProtocolMessageType('ListFloat32', (_message.Message,), dict(
  DESCRIPTOR = _LISTFLOAT32,
  __module__ = 'core_pb2'
  # @@protoc_insertion_point(class_scope:photon.ListFloat32)
  ))
_sym_db.RegisterMessage(ListFloat32)

ListFloat64 = _reflection.GeneratedProtocolMessageType('ListFloat64', (_message.Message,), dict(
  DESCRIPTOR = _LISTFLOAT64,
  __module__ = 'core_pb2'
  # @@protoc_insertion_point(class_scope:photon.ListFloat64)
  ))
_sym_db.RegisterMessage(ListFloat64)

EmptyRequest = _reflection.GeneratedProtocolMessageType('EmptyRequest', (_message.Message,), dict(
  DESCRIPTOR = _EMPTYREQUEST,
  __module__ = 'core_pb2'
  # @@protoc_insertion_point(class_scope:photon.EmptyRequest)
  ))
_sym_db.RegisterMessage(EmptyRequest)

EmptyResponse = _reflection.GeneratedProtocolMessageType('EmptyResponse', (_message.Message,), dict(
  DESCRIPTOR = _EMPTYRESPONSE,
  __module__ = 'core_pb2'
  # @@protoc_insertion_point(class_scope:photon.EmptyResponse)
  ))
_sym_db.RegisterMessage(EmptyResponse)

DataBlob = _reflection.GeneratedProtocolMessageType('DataBlob', (_message.Message,), dict(
  DESCRIPTOR = _DATABLOB,
  __module__ = 'core_pb2'
  # @@protoc_insertion_point(class_scope:photon.DataBlob)
  ))
_sym_db.RegisterMessage(DataBlob)


# @@protoc_insertion_point(module_scope)
