# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: evaluator.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import core_pb2 as core__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='evaluator.proto',
  package='photon',
  syntax='proto3',
  serialized_pb=_b('\n\x0f\x65valuator.proto\x12\x06photon\x1a\ncore.proto\"\xab\x01\n\x11\x45valuationRequest\x12\x12\n\nmodel_name\x18\x01 \x01(\t\x12\x39\n\x08\x66\x65\x61tures\x18\x02 \x03(\x0b\x32\'.photon.EvaluationRequest.FeaturesEntry\x1aG\n\rFeaturesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12%\n\x05value\x18\x02 \x01(\x0b\x32\x16.photon.ValueInterface:\x02\x38\x01\"\xc9\x01\n\x12\x45valuationResponse\x12\x11\n\tmodel_uid\x18\x01 \x01(\t\x12\x13\n\x0bversion_uid\x18\x02 \x01(\t\x12\x0c\n\x04node\x18\x03 \x01(\t\x12\x36\n\x06result\x18\x04 \x03(\x0b\x32&.photon.EvaluationResponse.ResultEntry\x1a\x45\n\x0bResultEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12%\n\x05value\x18\x02 \x01(\x0b\x32\x16.photon.ValueInterface:\x02\x38\x01\x32U\n\x10\x45valuatorService\x12\x41\n\x08\x45valuate\x12\x19.photon.EvaluationRequest\x1a\x1a.photon.EvaluationResponseb\x06proto3')
  ,
  dependencies=[core__pb2.DESCRIPTOR,])




_EVALUATIONREQUEST_FEATURESENTRY = _descriptor.Descriptor(
  name='FeaturesEntry',
  full_name='photon.EvaluationRequest.FeaturesEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='photon.EvaluationRequest.FeaturesEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='value', full_name='photon.EvaluationRequest.FeaturesEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=_descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('8\001')),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=140,
  serialized_end=211,
)

_EVALUATIONREQUEST = _descriptor.Descriptor(
  name='EvaluationRequest',
  full_name='photon.EvaluationRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='model_name', full_name='photon.EvaluationRequest.model_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='features', full_name='photon.EvaluationRequest.features', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_EVALUATIONREQUEST_FEATURESENTRY, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=40,
  serialized_end=211,
)


_EVALUATIONRESPONSE_RESULTENTRY = _descriptor.Descriptor(
  name='ResultEntry',
  full_name='photon.EvaluationResponse.ResultEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='photon.EvaluationResponse.ResultEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='value', full_name='photon.EvaluationResponse.ResultEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=_descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('8\001')),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=346,
  serialized_end=415,
)

_EVALUATIONRESPONSE = _descriptor.Descriptor(
  name='EvaluationResponse',
  full_name='photon.EvaluationResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='model_uid', full_name='photon.EvaluationResponse.model_uid', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='version_uid', full_name='photon.EvaluationResponse.version_uid', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='node', full_name='photon.EvaluationResponse.node', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='result', full_name='photon.EvaluationResponse.result', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_EVALUATIONRESPONSE_RESULTENTRY, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=214,
  serialized_end=415,
)

_EVALUATIONREQUEST_FEATURESENTRY.fields_by_name['value'].message_type = core__pb2._VALUEINTERFACE
_EVALUATIONREQUEST_FEATURESENTRY.containing_type = _EVALUATIONREQUEST
_EVALUATIONREQUEST.fields_by_name['features'].message_type = _EVALUATIONREQUEST_FEATURESENTRY
_EVALUATIONRESPONSE_RESULTENTRY.fields_by_name['value'].message_type = core__pb2._VALUEINTERFACE
_EVALUATIONRESPONSE_RESULTENTRY.containing_type = _EVALUATIONRESPONSE
_EVALUATIONRESPONSE.fields_by_name['result'].message_type = _EVALUATIONRESPONSE_RESULTENTRY
DESCRIPTOR.message_types_by_name['EvaluationRequest'] = _EVALUATIONREQUEST
DESCRIPTOR.message_types_by_name['EvaluationResponse'] = _EVALUATIONRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

EvaluationRequest = _reflection.GeneratedProtocolMessageType('EvaluationRequest', (_message.Message,), dict(

  FeaturesEntry = _reflection.GeneratedProtocolMessageType('FeaturesEntry', (_message.Message,), dict(
    DESCRIPTOR = _EVALUATIONREQUEST_FEATURESENTRY,
    __module__ = 'evaluator_pb2'
    # @@protoc_insertion_point(class_scope:photon.EvaluationRequest.FeaturesEntry)
    ))
  ,
  DESCRIPTOR = _EVALUATIONREQUEST,
  __module__ = 'evaluator_pb2'
  # @@protoc_insertion_point(class_scope:photon.EvaluationRequest)
  ))
_sym_db.RegisterMessage(EvaluationRequest)
_sym_db.RegisterMessage(EvaluationRequest.FeaturesEntry)

EvaluationResponse = _reflection.GeneratedProtocolMessageType('EvaluationResponse', (_message.Message,), dict(

  ResultEntry = _reflection.GeneratedProtocolMessageType('ResultEntry', (_message.Message,), dict(
    DESCRIPTOR = _EVALUATIONRESPONSE_RESULTENTRY,
    __module__ = 'evaluator_pb2'
    # @@protoc_insertion_point(class_scope:photon.EvaluationResponse.ResultEntry)
    ))
  ,
  DESCRIPTOR = _EVALUATIONRESPONSE,
  __module__ = 'evaluator_pb2'
  # @@protoc_insertion_point(class_scope:photon.EvaluationResponse)
  ))
_sym_db.RegisterMessage(EvaluationResponse)
_sym_db.RegisterMessage(EvaluationResponse.ResultEntry)


_EVALUATIONREQUEST_FEATURESENTRY.has_options = True
_EVALUATIONREQUEST_FEATURESENTRY._options = _descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('8\001'))
_EVALUATIONRESPONSE_RESULTENTRY.has_options = True
_EVALUATIONRESPONSE_RESULTENTRY._options = _descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('8\001'))
# @@protoc_insertion_point(module_scope)
