# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: features.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import core_pb2 as core__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='features.proto',
  package='photon',
  syntax='proto3',
  serialized_pb=_b('\n\x0e\x66\x65\x61tures.proto\x12\x06photon\x1a\ncore.proto\"\x85\x01\n\nFeatureSet\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0c\n\x04keys\x18\x03 \x03(\t\x12\'\n\x06\x66ields\x18\x04 \x03(\x0b\x32\x17.photon.FeatureSetField\x12\x12\n\ncreated_at\x18\x05 \x01(\x05\x12\x12\n\nupdated_at\x18\x06 \x01(\x05\"]\n\x0f\x46\x65\x61tureSetField\x12\x16\n\x0e\x66\x65\x61ture_set_id\x18\x01 \x01(\x03\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x12\n\nvalue_type\x18\x03 \x01(\t\x12\x10\n\x08nullable\x18\x04 \x01(\x08\"#\n\x15\x46indFeatureSetRequest\x12\n\n\x02id\x18\x01 \x01(\x03\"^\n\x17\x43reateFeatureSetRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0c\n\x04keys\x18\x02 \x03(\t\x12\'\n\x06\x66ields\x18\x03 \x03(\x0b\x32\x17.photon.FeatureSetField\"&\n\x18\x43reateFeatureSetResponse\x12\n\n\x02id\x18\x01 \x01(\x03\"%\n\x17\x44\x65leteFeatureSetRequest\x12\n\n\x02id\x18\x01 \x01(\x03\x32\x8f\x02\n\x0f\x46\x65\x61turesService\x12\x32\n\x04List\x12\x14.photon.EmptyRequest\x1a\x12.photon.FeatureSet0\x01\x12\x39\n\x04\x46ind\x12\x1d.photon.FindFeatureSetRequest\x1a\x12.photon.FeatureSet\x12K\n\x06\x43reate\x12\x1f.photon.CreateFeatureSetRequest\x1a .photon.CreateFeatureSetResponse\x12@\n\x06\x44\x65lete\x12\x1f.photon.DeleteFeatureSetRequest\x1a\x15.photon.EmptyResponseb\x06proto3')
  ,
  dependencies=[core__pb2.DESCRIPTOR,])




_FEATURESET = _descriptor.Descriptor(
  name='FeatureSet',
  full_name='photon.FeatureSet',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='photon.FeatureSet.id', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='name', full_name='photon.FeatureSet.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='keys', full_name='photon.FeatureSet.keys', index=2,
      number=3, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='fields', full_name='photon.FeatureSet.fields', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='created_at', full_name='photon.FeatureSet.created_at', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='updated_at', full_name='photon.FeatureSet.updated_at', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=39,
  serialized_end=172,
)


_FEATURESETFIELD = _descriptor.Descriptor(
  name='FeatureSetField',
  full_name='photon.FeatureSetField',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='feature_set_id', full_name='photon.FeatureSetField.feature_set_id', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='name', full_name='photon.FeatureSetField.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='value_type', full_name='photon.FeatureSetField.value_type', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='nullable', full_name='photon.FeatureSetField.nullable', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=174,
  serialized_end=267,
)


_FINDFEATURESETREQUEST = _descriptor.Descriptor(
  name='FindFeatureSetRequest',
  full_name='photon.FindFeatureSetRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='photon.FindFeatureSetRequest.id', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=269,
  serialized_end=304,
)


_CREATEFEATURESETREQUEST = _descriptor.Descriptor(
  name='CreateFeatureSetRequest',
  full_name='photon.CreateFeatureSetRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='photon.CreateFeatureSetRequest.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='keys', full_name='photon.CreateFeatureSetRequest.keys', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='fields', full_name='photon.CreateFeatureSetRequest.fields', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=306,
  serialized_end=400,
)


_CREATEFEATURESETRESPONSE = _descriptor.Descriptor(
  name='CreateFeatureSetResponse',
  full_name='photon.CreateFeatureSetResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='photon.CreateFeatureSetResponse.id', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=402,
  serialized_end=440,
)


_DELETEFEATURESETREQUEST = _descriptor.Descriptor(
  name='DeleteFeatureSetRequest',
  full_name='photon.DeleteFeatureSetRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='photon.DeleteFeatureSetRequest.id', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=442,
  serialized_end=479,
)

_FEATURESET.fields_by_name['fields'].message_type = _FEATURESETFIELD
_CREATEFEATURESETREQUEST.fields_by_name['fields'].message_type = _FEATURESETFIELD
DESCRIPTOR.message_types_by_name['FeatureSet'] = _FEATURESET
DESCRIPTOR.message_types_by_name['FeatureSetField'] = _FEATURESETFIELD
DESCRIPTOR.message_types_by_name['FindFeatureSetRequest'] = _FINDFEATURESETREQUEST
DESCRIPTOR.message_types_by_name['CreateFeatureSetRequest'] = _CREATEFEATURESETREQUEST
DESCRIPTOR.message_types_by_name['CreateFeatureSetResponse'] = _CREATEFEATURESETRESPONSE
DESCRIPTOR.message_types_by_name['DeleteFeatureSetRequest'] = _DELETEFEATURESETREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

FeatureSet = _reflection.GeneratedProtocolMessageType('FeatureSet', (_message.Message,), dict(
  DESCRIPTOR = _FEATURESET,
  __module__ = 'features_pb2'
  # @@protoc_insertion_point(class_scope:photon.FeatureSet)
  ))
_sym_db.RegisterMessage(FeatureSet)

FeatureSetField = _reflection.GeneratedProtocolMessageType('FeatureSetField', (_message.Message,), dict(
  DESCRIPTOR = _FEATURESETFIELD,
  __module__ = 'features_pb2'
  # @@protoc_insertion_point(class_scope:photon.FeatureSetField)
  ))
_sym_db.RegisterMessage(FeatureSetField)

FindFeatureSetRequest = _reflection.GeneratedProtocolMessageType('FindFeatureSetRequest', (_message.Message,), dict(
  DESCRIPTOR = _FINDFEATURESETREQUEST,
  __module__ = 'features_pb2'
  # @@protoc_insertion_point(class_scope:photon.FindFeatureSetRequest)
  ))
_sym_db.RegisterMessage(FindFeatureSetRequest)

CreateFeatureSetRequest = _reflection.GeneratedProtocolMessageType('CreateFeatureSetRequest', (_message.Message,), dict(
  DESCRIPTOR = _CREATEFEATURESETREQUEST,
  __module__ = 'features_pb2'
  # @@protoc_insertion_point(class_scope:photon.CreateFeatureSetRequest)
  ))
_sym_db.RegisterMessage(CreateFeatureSetRequest)

CreateFeatureSetResponse = _reflection.GeneratedProtocolMessageType('CreateFeatureSetResponse', (_message.Message,), dict(
  DESCRIPTOR = _CREATEFEATURESETRESPONSE,
  __module__ = 'features_pb2'
  # @@protoc_insertion_point(class_scope:photon.CreateFeatureSetResponse)
  ))
_sym_db.RegisterMessage(CreateFeatureSetResponse)

DeleteFeatureSetRequest = _reflection.GeneratedProtocolMessageType('DeleteFeatureSetRequest', (_message.Message,), dict(
  DESCRIPTOR = _DELETEFEATURESETREQUEST,
  __module__ = 'features_pb2'
  # @@protoc_insertion_point(class_scope:photon.DeleteFeatureSetRequest)
  ))
_sym_db.RegisterMessage(DeleteFeatureSetRequest)


# @@protoc_insertion_point(module_scope)
