# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: runner.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import core_pb2 as core__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='runner.proto',
  package='photon',
  syntax='proto3',
  serialized_pb=_b('\n\x0crunner.proto\x12\x06photon\x1a\ncore.proto\"\xb4\x01\n\x15RunnerEvaluateRequest\x12\x13\n\x0bversion_uid\x18\x01 \x01(\t\x12=\n\x08\x66\x65\x61tures\x18\x02 \x03(\x0b\x32+.photon.RunnerEvaluateRequest.FeaturesEntry\x1aG\n\rFeaturesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12%\n\x05value\x18\x02 \x01(\x0b\x32\x16.photon.ValueInterface:\x02\x38\x01\"\x9b\x01\n\x16RunnerEvaluateResponse\x12:\n\x06result\x18\x01 \x03(\x0b\x32*.photon.RunnerEvaluateResponse.ResultEntry\x1a\x45\n\x0bResultEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12%\n\x05value\x18\x02 \x01(\x0b\x32\x16.photon.ValueInterface:\x02\x38\x01\x32Z\n\rRunnerService\x12I\n\x08\x45valuate\x12\x1d.photon.RunnerEvaluateRequest\x1a\x1e.photon.RunnerEvaluateResponseb\x06proto3')
  ,
  dependencies=[core__pb2.DESCRIPTOR,])




_RUNNEREVALUATEREQUEST_FEATURESENTRY = _descriptor.Descriptor(
  name='FeaturesEntry',
  full_name='photon.RunnerEvaluateRequest.FeaturesEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='photon.RunnerEvaluateRequest.FeaturesEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='value', full_name='photon.RunnerEvaluateRequest.FeaturesEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=_descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('8\001')),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=146,
  serialized_end=217,
)

_RUNNEREVALUATEREQUEST = _descriptor.Descriptor(
  name='RunnerEvaluateRequest',
  full_name='photon.RunnerEvaluateRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='version_uid', full_name='photon.RunnerEvaluateRequest.version_uid', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='features', full_name='photon.RunnerEvaluateRequest.features', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_RUNNEREVALUATEREQUEST_FEATURESENTRY, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=37,
  serialized_end=217,
)


_RUNNEREVALUATERESPONSE_RESULTENTRY = _descriptor.Descriptor(
  name='ResultEntry',
  full_name='photon.RunnerEvaluateResponse.ResultEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='photon.RunnerEvaluateResponse.ResultEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='value', full_name='photon.RunnerEvaluateResponse.ResultEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=_descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('8\001')),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=306,
  serialized_end=375,
)

_RUNNEREVALUATERESPONSE = _descriptor.Descriptor(
  name='RunnerEvaluateResponse',
  full_name='photon.RunnerEvaluateResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='photon.RunnerEvaluateResponse.result', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_RUNNEREVALUATERESPONSE_RESULTENTRY, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=220,
  serialized_end=375,
)

_RUNNEREVALUATEREQUEST_FEATURESENTRY.fields_by_name['value'].message_type = core__pb2._VALUEINTERFACE
_RUNNEREVALUATEREQUEST_FEATURESENTRY.containing_type = _RUNNEREVALUATEREQUEST
_RUNNEREVALUATEREQUEST.fields_by_name['features'].message_type = _RUNNEREVALUATEREQUEST_FEATURESENTRY
_RUNNEREVALUATERESPONSE_RESULTENTRY.fields_by_name['value'].message_type = core__pb2._VALUEINTERFACE
_RUNNEREVALUATERESPONSE_RESULTENTRY.containing_type = _RUNNEREVALUATERESPONSE
_RUNNEREVALUATERESPONSE.fields_by_name['result'].message_type = _RUNNEREVALUATERESPONSE_RESULTENTRY
DESCRIPTOR.message_types_by_name['RunnerEvaluateRequest'] = _RUNNEREVALUATEREQUEST
DESCRIPTOR.message_types_by_name['RunnerEvaluateResponse'] = _RUNNEREVALUATERESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RunnerEvaluateRequest = _reflection.GeneratedProtocolMessageType('RunnerEvaluateRequest', (_message.Message,), dict(

  FeaturesEntry = _reflection.GeneratedProtocolMessageType('FeaturesEntry', (_message.Message,), dict(
    DESCRIPTOR = _RUNNEREVALUATEREQUEST_FEATURESENTRY,
    __module__ = 'runner_pb2'
    # @@protoc_insertion_point(class_scope:photon.RunnerEvaluateRequest.FeaturesEntry)
    ))
  ,
  DESCRIPTOR = _RUNNEREVALUATEREQUEST,
  __module__ = 'runner_pb2'
  # @@protoc_insertion_point(class_scope:photon.RunnerEvaluateRequest)
  ))
_sym_db.RegisterMessage(RunnerEvaluateRequest)
_sym_db.RegisterMessage(RunnerEvaluateRequest.FeaturesEntry)

RunnerEvaluateResponse = _reflection.GeneratedProtocolMessageType('RunnerEvaluateResponse', (_message.Message,), dict(

  ResultEntry = _reflection.GeneratedProtocolMessageType('ResultEntry', (_message.Message,), dict(
    DESCRIPTOR = _RUNNEREVALUATERESPONSE_RESULTENTRY,
    __module__ = 'runner_pb2'
    # @@protoc_insertion_point(class_scope:photon.RunnerEvaluateResponse.ResultEntry)
    ))
  ,
  DESCRIPTOR = _RUNNEREVALUATERESPONSE,
  __module__ = 'runner_pb2'
  # @@protoc_insertion_point(class_scope:photon.RunnerEvaluateResponse)
  ))
_sym_db.RegisterMessage(RunnerEvaluateResponse)
_sym_db.RegisterMessage(RunnerEvaluateResponse.ResultEntry)


_RUNNEREVALUATEREQUEST_FEATURESENTRY.has_options = True
_RUNNEREVALUATEREQUEST_FEATURESENTRY._options = _descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('8\001'))
_RUNNEREVALUATERESPONSE_RESULTENTRY.has_options = True
_RUNNEREVALUATERESPONSE_RESULTENTRY._options = _descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('8\001'))
# @@protoc_insertion_point(module_scope)
