// Code generated by MockGen. DO NOT EDIT.
// Source: repositories/deployer_repository.go

// Package mock_repositories is a generated GoMock package.
package mock_repositories

import (
	gomock "github.com/golang/mock/gomock"
	zk "github.com/samuel/go-zookeeper/zk"
	reflect "reflect"
)

// MockDeployerRepository is a mock of DeployerRepository interface
type MockDeployerRepository struct {
	ctrl     *gomock.Controller
	recorder *MockDeployerRepositoryMockRecorder
}

// MockDeployerRepositoryMockRecorder is the mock recorder for MockDeployerRepository
type MockDeployerRepositoryMockRecorder struct {
	mock *MockDeployerRepository
}

// NewMockDeployerRepository creates a new mock instance
func NewMockDeployerRepository(ctrl *gomock.Controller) *MockDeployerRepository {
	mock := &MockDeployerRepository{ctrl: ctrl}
	mock.recorder = &MockDeployerRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockDeployerRepository) EXPECT() *MockDeployerRepositoryMockRecorder {
	return m.recorder
}

// ListVersionsW mocks base method
func (m *MockDeployerRepository) ListVersionsW(arg0, arg1 string) (map[string]string, <-chan zk.Event, error) {
	ret := m.ctrl.Call(m, "ListVersionsW", arg0, arg1)
	ret0, _ := ret[0].(map[string]string)
	ret1, _ := ret[1].(<-chan zk.Event)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListVersionsW indicates an expected call of ListVersionsW
func (mr *MockDeployerRepositoryMockRecorder) ListVersionsW(arg0, arg1 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListVersionsW", reflect.TypeOf((*MockDeployerRepository)(nil).ListVersionsW), arg0, arg1)
}

// ModelPathExistsW mocks base method
func (m *MockDeployerRepository) ModelPathExistsW(arg0, arg1 string) (bool, <-chan zk.Event, error) {
	ret := m.ctrl.Call(m, "ModelPathExistsW", arg0, arg1)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(<-chan zk.Event)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ModelPathExistsW indicates an expected call of ModelPathExistsW
func (mr *MockDeployerRepositoryMockRecorder) ModelPathExistsW(arg0, arg1 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ModelPathExistsW", reflect.TypeOf((*MockDeployerRepository)(nil).ModelPathExistsW), arg0, arg1)
}
