version: '2'
 
services:
  mysql:
    image: mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    ports:
      - 3306:3306
  cassandra:
    image: cassandra:3.0.8
    volumes:
      - /var/lib/cassandra
    ports:
      - "7000:7000"
      - "7001:7001"
      - "7199:7199"
      - "9042:9042"
      - "9160:9160"
  zookeeper:
    image: zookeeper
    ports:
        - 2181:2181
