// Code generated by protoc-gen-go. DO NOT EDIT.
// source: features.proto

package photon

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type FeatureSet struct {
	Id        int64              `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Name      string             `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Keys      []string           `protobuf:"bytes,3,rep,name=keys" json:"keys,omitempty"`
	Fields    []*FeatureSetField `protobuf:"bytes,4,rep,name=fields" json:"fields,omitempty"`
	CreatedAt int32              `protobuf:"varint,5,opt,name=created_at,json=createdAt" json:"created_at,omitempty"`
	UpdatedAt int32              `protobuf:"varint,6,opt,name=updated_at,json=updatedAt" json:"updated_at,omitempty"`
}

func (m *FeatureSet) Reset()                    { *m = FeatureSet{} }
func (m *FeatureSet) String() string            { return proto.CompactTextString(m) }
func (*FeatureSet) ProtoMessage()               {}
func (*FeatureSet) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{0} }

func (m *FeatureSet) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *FeatureSet) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *FeatureSet) GetKeys() []string {
	if m != nil {
		return m.Keys
	}
	return nil
}

func (m *FeatureSet) GetFields() []*FeatureSetField {
	if m != nil {
		return m.Fields
	}
	return nil
}

func (m *FeatureSet) GetCreatedAt() int32 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func (m *FeatureSet) GetUpdatedAt() int32 {
	if m != nil {
		return m.UpdatedAt
	}
	return 0
}

type FeatureSetField struct {
	FeatureSetId int64  `protobuf:"varint,1,opt,name=feature_set_id,json=featureSetId" json:"feature_set_id,omitempty"`
	Name         string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	ValueType    string `protobuf:"bytes,3,opt,name=value_type,json=valueType" json:"value_type,omitempty"`
	Nullable     bool   `protobuf:"varint,4,opt,name=nullable" json:"nullable,omitempty"`
}

func (m *FeatureSetField) Reset()                    { *m = FeatureSetField{} }
func (m *FeatureSetField) String() string            { return proto.CompactTextString(m) }
func (*FeatureSetField) ProtoMessage()               {}
func (*FeatureSetField) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{1} }

func (m *FeatureSetField) GetFeatureSetId() int64 {
	if m != nil {
		return m.FeatureSetId
	}
	return 0
}

func (m *FeatureSetField) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *FeatureSetField) GetValueType() string {
	if m != nil {
		return m.ValueType
	}
	return ""
}

func (m *FeatureSetField) GetNullable() bool {
	if m != nil {
		return m.Nullable
	}
	return false
}

type FindFeatureSetRequest struct {
	Id int64 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
}

func (m *FindFeatureSetRequest) Reset()                    { *m = FindFeatureSetRequest{} }
func (m *FindFeatureSetRequest) String() string            { return proto.CompactTextString(m) }
func (*FindFeatureSetRequest) ProtoMessage()               {}
func (*FindFeatureSetRequest) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{2} }

func (m *FindFeatureSetRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type CreateFeatureSetRequest struct {
	Name   string             `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Keys   []string           `protobuf:"bytes,2,rep,name=keys" json:"keys,omitempty"`
	Fields []*FeatureSetField `protobuf:"bytes,3,rep,name=fields" json:"fields,omitempty"`
}

func (m *CreateFeatureSetRequest) Reset()                    { *m = CreateFeatureSetRequest{} }
func (m *CreateFeatureSetRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateFeatureSetRequest) ProtoMessage()               {}
func (*CreateFeatureSetRequest) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{3} }

func (m *CreateFeatureSetRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateFeatureSetRequest) GetKeys() []string {
	if m != nil {
		return m.Keys
	}
	return nil
}

func (m *CreateFeatureSetRequest) GetFields() []*FeatureSetField {
	if m != nil {
		return m.Fields
	}
	return nil
}

type CreateFeatureSetResponse struct {
	Id int64 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
}

func (m *CreateFeatureSetResponse) Reset()                    { *m = CreateFeatureSetResponse{} }
func (m *CreateFeatureSetResponse) String() string            { return proto.CompactTextString(m) }
func (*CreateFeatureSetResponse) ProtoMessage()               {}
func (*CreateFeatureSetResponse) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{4} }

func (m *CreateFeatureSetResponse) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type DeleteFeatureSetRequest struct {
	Id int64 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
}

func (m *DeleteFeatureSetRequest) Reset()                    { *m = DeleteFeatureSetRequest{} }
func (m *DeleteFeatureSetRequest) String() string            { return proto.CompactTextString(m) }
func (*DeleteFeatureSetRequest) ProtoMessage()               {}
func (*DeleteFeatureSetRequest) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{5} }

func (m *DeleteFeatureSetRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func init() {
	proto.RegisterType((*FeatureSet)(nil), "photon.FeatureSet")
	proto.RegisterType((*FeatureSetField)(nil), "photon.FeatureSetField")
	proto.RegisterType((*FindFeatureSetRequest)(nil), "photon.FindFeatureSetRequest")
	proto.RegisterType((*CreateFeatureSetRequest)(nil), "photon.CreateFeatureSetRequest")
	proto.RegisterType((*CreateFeatureSetResponse)(nil), "photon.CreateFeatureSetResponse")
	proto.RegisterType((*DeleteFeatureSetRequest)(nil), "photon.DeleteFeatureSetRequest")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for FeaturesService service

type FeaturesServiceClient interface {
	List(ctx context.Context, in *EmptyRequest, opts ...grpc.CallOption) (FeaturesService_ListClient, error)
	Find(ctx context.Context, in *FindFeatureSetRequest, opts ...grpc.CallOption) (*FeatureSet, error)
	Create(ctx context.Context, in *CreateFeatureSetRequest, opts ...grpc.CallOption) (*CreateFeatureSetResponse, error)
	Delete(ctx context.Context, in *DeleteFeatureSetRequest, opts ...grpc.CallOption) (*EmptyResponse, error)
}

type featuresServiceClient struct {
	cc *grpc.ClientConn
}

func NewFeaturesServiceClient(cc *grpc.ClientConn) FeaturesServiceClient {
	return &featuresServiceClient{cc}
}

func (c *featuresServiceClient) List(ctx context.Context, in *EmptyRequest, opts ...grpc.CallOption) (FeaturesService_ListClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_FeaturesService_serviceDesc.Streams[0], c.cc, "/photon.FeaturesService/List", opts...)
	if err != nil {
		return nil, err
	}
	x := &featuresServiceListClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type FeaturesService_ListClient interface {
	Recv() (*FeatureSet, error)
	grpc.ClientStream
}

type featuresServiceListClient struct {
	grpc.ClientStream
}

func (x *featuresServiceListClient) Recv() (*FeatureSet, error) {
	m := new(FeatureSet)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *featuresServiceClient) Find(ctx context.Context, in *FindFeatureSetRequest, opts ...grpc.CallOption) (*FeatureSet, error) {
	out := new(FeatureSet)
	err := grpc.Invoke(ctx, "/photon.FeaturesService/Find", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *featuresServiceClient) Create(ctx context.Context, in *CreateFeatureSetRequest, opts ...grpc.CallOption) (*CreateFeatureSetResponse, error) {
	out := new(CreateFeatureSetResponse)
	err := grpc.Invoke(ctx, "/photon.FeaturesService/Create", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *featuresServiceClient) Delete(ctx context.Context, in *DeleteFeatureSetRequest, opts ...grpc.CallOption) (*EmptyResponse, error) {
	out := new(EmptyResponse)
	err := grpc.Invoke(ctx, "/photon.FeaturesService/Delete", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for FeaturesService service

type FeaturesServiceServer interface {
	List(*EmptyRequest, FeaturesService_ListServer) error
	Find(context.Context, *FindFeatureSetRequest) (*FeatureSet, error)
	Create(context.Context, *CreateFeatureSetRequest) (*CreateFeatureSetResponse, error)
	Delete(context.Context, *DeleteFeatureSetRequest) (*EmptyResponse, error)
}

func RegisterFeaturesServiceServer(s *grpc.Server, srv FeaturesServiceServer) {
	s.RegisterService(&_FeaturesService_serviceDesc, srv)
}

func _FeaturesService_List_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(EmptyRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(FeaturesServiceServer).List(m, &featuresServiceListServer{stream})
}

type FeaturesService_ListServer interface {
	Send(*FeatureSet) error
	grpc.ServerStream
}

type featuresServiceListServer struct {
	grpc.ServerStream
}

func (x *featuresServiceListServer) Send(m *FeatureSet) error {
	return x.ServerStream.SendMsg(m)
}

func _FeaturesService_Find_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindFeatureSetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FeaturesServiceServer).Find(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/photon.FeaturesService/Find",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FeaturesServiceServer).Find(ctx, req.(*FindFeatureSetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FeaturesService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateFeatureSetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FeaturesServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/photon.FeaturesService/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FeaturesServiceServer).Create(ctx, req.(*CreateFeatureSetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FeaturesService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteFeatureSetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FeaturesServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/photon.FeaturesService/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FeaturesServiceServer).Delete(ctx, req.(*DeleteFeatureSetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _FeaturesService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "photon.FeaturesService",
	HandlerType: (*FeaturesServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Find",
			Handler:    _FeaturesService_Find_Handler,
		},
		{
			MethodName: "Create",
			Handler:    _FeaturesService_Create_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _FeaturesService_Delete_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "List",
			Handler:       _FeaturesService_List_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "features.proto",
}

func init() { proto.RegisterFile("features.proto", fileDescriptor2) }

var fileDescriptor2 = []byte{
	// 389 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x53, 0x4f, 0x6b, 0xa3, 0x40,
	0x1c, 0x65, 0xd4, 0x48, 0xf2, 0xdb, 0x25, 0x0b, 0x3f, 0x36, 0x64, 0x10, 0xc2, 0x8a, 0x2c, 0xac,
	0xbb, 0x87, 0x6c, 0x49, 0x4f, 0xbd, 0x35, 0xb4, 0x0d, 0x94, 0xf6, 0x64, 0x7a, 0x17, 0x13, 0x7f,
	0xa1, 0x52, 0xa3, 0xd6, 0x19, 0x03, 0x7e, 0x81, 0x5e, 0xfb, 0x61, 0xfa, 0x05, 0x8b, 0x7f, 0x03,
	0xd1, 0x40, 0x6f, 0xe3, 0x7b, 0xcf, 0x37, 0xef, 0x3d, 0x18, 0x18, 0xef, 0xc8, 0x93, 0x59, 0x4a,
	0x62, 0x9e, 0xa4, 0xb1, 0x8c, 0x51, 0x4f, 0x9e, 0x63, 0x19, 0x47, 0x06, 0x6c, 0xe3, 0x94, 0x2a,
	0xcc, 0xfa, 0x60, 0x00, 0xab, 0x4a, 0xb6, 0x26, 0x89, 0x63, 0x50, 0x02, 0x9f, 0x33, 0x93, 0xd9,
	0xaa, 0xa3, 0x04, 0x3e, 0x22, 0x68, 0x91, 0xb7, 0x27, 0xae, 0x98, 0xcc, 0x1e, 0x39, 0xe5, 0xb9,
	0xc0, 0x5e, 0x28, 0x17, 0x5c, 0x35, 0xd5, 0x02, 0x2b, 0xce, 0xf8, 0x1f, 0xf4, 0x5d, 0x40, 0xa1,
	0x2f, 0xb8, 0x66, 0xaa, 0xf6, 0xb7, 0xc5, 0x74, 0x5e, 0xdd, 0x35, 0x3f, 0x7a, 0xaf, 0x0a, 0xde,
	0xa9, 0x65, 0x38, 0x03, 0xd8, 0xa6, 0xe4, 0x49, 0xf2, 0x5d, 0x4f, 0xf2, 0x81, 0xc9, 0xec, 0x81,
	0x33, 0xaa, 0x91, 0xa5, 0x2c, 0xe8, 0x2c, 0xf1, 0x1b, 0x5a, 0xaf, 0xe8, 0x1a, 0x59, 0x4a, 0xeb,
	0x8d, 0xc1, 0x8f, 0x13, 0x67, 0xfc, 0xdd, 0xf6, 0x75, 0x05, 0x49, 0xb7, 0xad, 0xf1, 0x7d, 0xd7,
	0x0a, 0xef, 0xfb, 0x0b, 0xcd, 0x00, 0x0e, 0x5e, 0x98, 0x91, 0x2b, 0xf3, 0x84, 0xb8, 0x5a, 0x32,
	0xa3, 0x12, 0x79, 0xca, 0x13, 0x42, 0x03, 0x86, 0x51, 0x16, 0x86, 0xde, 0x26, 0x24, 0xae, 0x99,
	0xcc, 0x1e, 0x3a, 0xed, 0xb7, 0xf5, 0x07, 0x26, 0xab, 0x20, 0xf2, 0x8f, 0x59, 0x1c, 0x7a, 0xcd,
	0x48, 0x74, 0x86, 0xb4, 0x52, 0x98, 0xde, 0x94, 0xed, 0xba, 0xd2, 0x26, 0x12, 0xeb, 0xd9, 0x58,
	0xe9, 0xdd, 0x58, 0xfd, 0xd2, 0xc6, 0xd6, 0x3f, 0xe0, 0xdd, 0x3b, 0x45, 0x12, 0x47, 0x82, 0x3a,
	0xf9, 0xfe, 0xc2, 0xf4, 0x96, 0x42, 0xea, 0xcb, 0x77, 0x22, 0x5d, 0xbc, 0x2b, 0xed, 0xf8, 0x62,
	0x4d, 0xe9, 0x21, 0xd8, 0x12, 0x2e, 0x40, 0x7b, 0x0c, 0x84, 0xc4, 0x9f, 0x4d, 0xa6, 0xbb, 0x7d,
	0x22, 0xf3, 0xda, 0xc1, 0xc0, 0x6e, 0xd2, 0x0b, 0x86, 0x57, 0xa0, 0x15, 0xdb, 0xe1, 0xac, 0x65,
	0xfb, 0x96, 0xec, 0xfb, 0x19, 0x1f, 0x40, 0xaf, 0x9a, 0xe1, 0xaf, 0x86, 0x3d, 0xb3, 0xae, 0x61,
	0x9e, 0x17, 0xd4, 0x53, 0x5c, 0x83, 0x5e, 0x55, 0x3f, 0x9a, 0x9d, 0x99, 0xc2, 0x98, 0x9c, 0xd4,
	0xab, 0x1c, 0x36, 0x7a, 0xf9, 0x96, 0x2e, 0x3f, 0x03, 0x00, 0x00, 0xff, 0xff, 0x15, 0x76, 0x7a,
	0x04, 0x71, 0x03, 0x00, 0x00,
}
