FROM golang:1.8-alpine

RUN apk --update add curl bash build-base git pkgconfig
RUN mkdir /photon

COPY ./core /go/src/github.com/marekgalovic/photon/go/core
COPY ./deployer /go/src/github.com/marekgalovic/photon/go/deployer
COPY ./cmd/deployer /photon

WORKDIR /photon
RUN go get -t -d -v ./...
RUN go build -o ./deployer ./main.go
RUN chmod +x ./deployer

CMD ["/photon/deployer"]
